version: 0.2
phases:
    build:
        commands:
          - echo Hello World!
          - aws s3 cp ./template.yaml s3://rigd-tools-east/HWTemplate.yaml
artifacts:
    files:
      - '__init__.py'
      - 'HelloWorld.py'
